import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:tracker_flutter/features/auth/application/auth_service.dart';
import 'package:tracker_flutter/features/vehicle/data/vehicle_repository.dart';
import 'package:tracker_flutter/features/vehicle/domain/vehicle.dart';

final vehicleRepositoryProvider = Provider<VehicleRepository?>((ref) {
  final authState = ref.watch(authStateProvider);
  final user = authState.value;
  if (user == null) return null;
  return VehicleRepository(FirebaseFirestore.instance, user.id);
});

final vehiclesStreamProvider = StreamProvider<List<Vehicle>>((ref) {
  final repository = ref.watch(vehicleRepositoryProvider);
  if (repository == null) return Stream.value([]);
  return repository.watchVehicles();
});

class VehicleController extends StateNotifier<AsyncValue<void>> {
  final VehicleRepository? _repository;

  VehicleController(this._repository) : super(const AsyncData(null));

  Future<void> addVehicle({
    required String name,
    required String brand,
    required String model,
    required String plateNumber,
    required int currentMileage,
  }) async {
    if (_repository == null) return;
    state = const AsyncLoading();
    final vehicle = Vehicle(
      id: '', // Generated by Firestore
      name: name,
      brand: brand,
      model: model,
      plateNumber: plateNumber,
      currentMileage: currentMileage,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );
    state = await AsyncValue.guard(() => _repository.addVehicle(vehicle));
  }
}

final vehicleControllerProvider = StateNotifierProvider<VehicleController, AsyncValue<void>>((ref) {
  return VehicleController(ref.watch(vehicleRepositoryProvider));
});
