// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxPT30guLA3l0gZT64PiRO7sOTkG1KROA',
    appId: '1:261451785542:ios:390cf56a425d4a561c7147',
    messagingSenderId: '261451785542',
    projectId: 'tracker-flutter-253f5',
    storageBucket: 'tracker-flutter-253f5.firebasestorage.app',
    iosBundleId: 'esisa.ac.ma.trackerFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxPT30guLA3l0gZT64PiRO7sOTkG1KROA',
    appId: '1:261451785542:ios:390cf56a425d4a561c7147',
    messagingSenderId: '261451785542',
    projectId: 'tracker-flutter-253f5',
    storageBucket: 'tracker-flutter-253f5.firebasestorage.app',
    iosBundleId: 'esisa.ac.ma.trackerFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIJHAKjb_9rijVNP195Ceov87t6TJTYLs',
    appId: '1:261451785542:web:23872d09e01ba58b1c7147',
    messagingSenderId: '261451785542',
    projectId: 'tracker-flutter-253f5',
    authDomain: 'tracker-flutter-253f5.firebaseapp.com',
    storageBucket: 'tracker-flutter-253f5.firebasestorage.app',
    measurementId: 'G-M33XGFV5JB',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIJHAKjb_9rijVNP195Ceov87t6TJTYLs',
    appId: '1:261451785542:web:23872d09e01ba58b1c7147',
    messagingSenderId: '261451785542',
    projectId: 'tracker-flutter-253f5',
    authDomain: 'tracker-flutter-253f5.firebaseapp.com',
    storageBucket: 'tracker-flutter-253f5.firebasestorage.app',
    measurementId: 'G-M33XGFV5JB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWb_t_a7DwxCL2hpntil-_LlyvpCGL-ko',
    appId: '1:261451785542:android:693dcbf02a6c59171c7147',
    messagingSenderId: '261451785542',
    projectId: 'tracker-flutter-253f5',
    storageBucket: 'tracker-flutter-253f5.firebasestorage.app',
  );

}